package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"
	"fokus-app/graph/model"
	"time"
)

// CreateFocusarea is the resolver for the createFocusarea field.
func (r *mutationResolver) CreateFocusarea(ctx context.Context, name string, deadline *string) (*model.Focusarea, error) {
	newFocusarea := &model.Focusarea{
		ID:       fmt.Sprintf("focusarea-%d", len(r.focusareas)+1),
		Name:     name,
		Deadline: deadline,
	}

	r.focusareas = append(r.focusareas, newFocusarea)
	return newFocusarea, nil
}

// StartSession is the resolver for the startSession field.
func (r *mutationResolver) StartSession(ctx context.Context, focusareaID string) (*model.Session, error) {
	newSession := &model.Session{
		ID:              fmt.Sprintf("session-%d", len(r.sessions)+1),
		FocusareaID:     focusareaID,
		Start:           time.Now().Format(time.RFC3339),
		End:             nil,
		DurationMinutes: nil,
	}

	r.sessions = append(r.sessions, newSession)
	return newSession, nil
}

// StopSession is the resolver for the stopSession field.
func (r *mutationResolver) StopSession(ctx context.Context) (*model.Session, error) {
	if len(r.sessions) == 0 {
		return nil, fmt.Errorf("no active session to stop")
	}

	lastSession := r.sessions[len(r.sessions)-1]

	if lastSession.End != nil {
		return nil, fmt.Errorf("last session already stopped")
	}

	endTime := time.Now()
	startTime, err := time.Parse(time.RFC3339, lastSession.Start)
	if err != nil {
		return nil, fmt.Errorf("invalid start time: %v", err)
	}

	duration := int32(endTime.Sub(startTime).Minutes())
	endTimeStr := endTime.Format(time.RFC3339)

	lastSession.End = &endTimeStr
	lastSession.DurationMinutes = &duration

	return lastSession, nil
}

// Focusarea is the resolver for the focusarea field.
func (r *queryResolver) Focusarea(ctx context.Context) ([]*model.Focusarea, error) {
	return r.focusareas, nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context) ([]*model.Session, error) {
	return r.sessions, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
