package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fokus-app/graph/model"
)

// CreateFocusarea is the resolver for the createFocusarea field.
func (r *mutationResolver) CreateFocusarea(ctx context.Context, name string, deadline *string) (*model.Focusarea, error) {
	return r.Resolver.focusareaService.CreateFocusarea(name, deadline)
}

// StartSession is the resolver for the startSession field.
func (r *mutationResolver) StartSession(ctx context.Context, focusareaID string) (*model.Session, error) {
	return r.Resolver.sessionService.CreateSession(focusareaID)
}

// StopSession is the resolver for the stopSession field.
func (r *mutationResolver) StopSession(ctx context.Context) (*model.Session, error) {
	return r.Resolver.sessionService.StopSession()
}

// Focusarea is the resolver for the focusarea field.
func (r *queryResolver) Focusarea(ctx context.Context) ([]*model.Focusarea, error) {
	return r.Resolver.focusareaService.GetAllFocusareas()
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context) ([]*model.Session, error) {
	return r.Resolver.sessionService.GetAllSessions()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
