package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"

	"github.com/Thyriion/fokus-app/graph/model"
)

// CreateFocusarea is the resolver for the createFocusarea field.
func (r *mutationResolver) CreateFocusarea(ctx context.Context, name string, deadline *string) (*model.Focusarea, error) {
	newFocusarea := &model.Focusarea{
		ID:       fmt.Sprintf("focusarea-%d", len(r.focusareas)+1),
		Name:     name,
		Deadline: deadline,
	}

	r.focusareas = append(r.focusareas, newFocusarea)
	return newFocusarea, nil
}

// Focusarea is the resolver for the focusarea field.
func (r *queryResolver) Focusarea(ctx context.Context) ([]*model.Focusarea, error) {
	return r.focusareas, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
