// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Focusarea struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Deadline *string `json:"deadline,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
