// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Focusarea struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Deadline *string `json:"deadline,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Session struct {
	ID              string  `json:"id"`
	FocusareaID     string  `json:"focusareaId"`
	Start           string  `json:"start"`
	End             *string `json:"end,omitempty"`
	DurationMinutes *int32  `json:"durationMinutes,omitempty"`
}
